# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 07:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_registration', models.IntegerField(default=0)),
                ('cost_transportation', models.IntegerField(default=0)),
                ('cost_accomodation', models.IntegerField(default=0)),
                ('cost_meals', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2016, 12, 5, 7, 8, 57, 202693))),
                ('last_edited', models.DateTimeField(default=datetime.datetime(2016, 12, 5, 7, 8, 57, 202725))),
                ('status', models.CharField(choices=[('R', 'Rejected'), ('P', 'Pending Faculty Approval'), ('C', 'Changes Requested'), ('S', 'Submitted'), ('I', 'Incomplete')], default='I', max_length=1)),
            ],
            options={
                'db_table': 'Application',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'Conference',
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('sessions_completed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('thesis_topic', models.CharField(max_length=300)),
                ('bank_account_number', models.CharField(max_length=20, unique=True)),
                ('is_eligible_for_grant', models.BooleanField(default=True)),
                ('type_of_requester', models.CharField(choices=[('M', 'Masters'), ('P', 'PhD'), ('F', 'Fast Track')], max_length=1)),
            ],
            options={
                'db_table': 'Requester',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Supervisor',
            },
        ),
        migrations.AddField(
            model_name='requester',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Supervisor'),
        ),
        migrations.AddField(
            model_name='requester',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Conference'),
        ),
        migrations.AddField(
            model_name='application',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Requester'),
        ),
    ]
