# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserType',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 4, 14, 33, 29, 247081)),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='total_amount_requested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table='Supervisor',
        ),
    ]
